---
  - ec2_remote_facts:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        filters:
         instance-id: ec2_facts.instances.id 
    register: ec2_facts
    ignore_errors: yes

  - debug:
        var: ec2_facts

  - ec2:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance-id: i-01894860eb512dbdf
        state: absent
